Update storage firewall config
RSE-Cambridge/cumulus-kayobe-config pull request #56
Opened 2019-05-14 11:35 UTC by jovial

Hmm, quite a lot of churn here. Does ceph use ephemeral ports? Or can we rely on these to stay static across reboots?

2019-05-14 13:14 UTC, JohnGarbutt requested changes
oh, nice, that is much better now.

Should we now stop the host specific files, as it should the same for all of them now we have the range?

2019-05-14 13:20 UTC, jovial commented
> oh, nice, that is much better now.
> 
> Should we now stop the host specific files, as it should the same for all of them now we have the range?

The only difference is that only one of the nodes (ceph01) seems to run the ceph-mgr service:

```
[will@cumulus-seed hosts_vars]$ diff -Naur ceph01 ceph03
--- ceph01      2019-05-14 13:09:23.076097322 +0000
+++ ceph03      2019-05-14 13:09:23.076097322 +0000
@@ -3,10 +3,6 @@
 firewallgen_enable_firewall: True
 
 firewallgen_ipv4_input_allow_rules:
-  - interface: "all"
-    port: 9283
-    proto: tcp
-    comment: "hint: used by 'ceph-mgr'"
   - interface: "lo"
     port: 25
     proto: tcp
```

I will update to use the `ceph01` config for all of the nodes.

2019-05-14 15:14 UTC, JohnGarbutt commented on etc/kayobe/inventory/group_vars/ceph/firewall
> +  - interface: "all"
I don't think this is correct, although certainly that is what the service is doing.

I think it should be storage management net only, but... you know, I am probably wrong.

2019-05-29 10:21 UTC, JohnGarbutt approved these changes

2019-05-29 10:21 UTC, merged