Add static route back to internal-to-storage router on storage nodes
RSE-Cambridge/cumulus-kayobe-config pull request #71
Opened 2019-08-07 13:02 UTC by jovial

2019-08-07 13:53 UTC, JohnGarbutt approved these changes

2019-08-07 13:53 UTC, JohnGarbutt commented on etc/kayobe/inventory/group_vars/ceph/network-interfaces
> +  - cidr: "10.215.215.0/24"
Looks good, should we add the 10.218 in there too?

2019-09-25 12:59 UTC, JohnGarbutt requested changes
Actually given the recent changes we removed the 10.215 network, so we need to add the route for the 10.208 networking, I think.

2019-10-08 11:33 UTC, paulbrowne commented
I added the static route from storage 206 to provider network 218 in this PR to capture it in the config;

https://github.com/RSE-Cambridge/cumulus-kayobe-config/pull/79/files#r332463010

2019-10-08 11:36 UTC, jovial commented
Thanks, looks like I can close this one now then.

2019-10-08 11:36 UTC, closed without merging